package classe;
// Generated 2016-11-30 12:27:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Typemembre generated by hbm2java
 */
public class Typemembre  implements java.io.Serializable {


     private Integer idtypemembre;
     private String typemem;
     private Set membres = new HashSet(0);

    public Typemembre() {
    }

	
    public Typemembre(String typemem) {
        this.typemem = typemem;
    }
    public Typemembre(String typemem, Set membres) {
       this.typemem = typemem;
       this.membres = membres;
    }
   
    public Integer getIdtypemembre() {
        return this.idtypemembre;
    }
    
    public void setIdtypemembre(Integer idtypemembre) {
        this.idtypemembre = idtypemembre;
    }
    public String getTypemem() {
        return this.typemem;
    }
    
    public void setTypemem(String typemem) {
        this.typemem = typemem;
    }
    public Set getMembres() {
        return this.membres;
    }
    
    public void setMembres(Set membres) {
        this.membres = membres;
    }




}


