package classe;
// Generated 2016-12-05 17:18:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Membre generated by hbm2java
 */
public class Membre  implements java.io.Serializable {


     private Integer idmembre;
     private Typemembre typemembre;
     private String email;
     private String mpd;
     private String nomutil;
     private int restoPref;
     private int typecuisinePref;
     private Set restaurants = new HashSet(0);
     private Set commentaires = new HashSet(0);
     private Set typecuisines = new HashSet(0);

    public Membre() {
    }

	
    public Membre(Typemembre typemembre, String email, String mpd, String nomutil, int restoPref, int typecuisinePref) {
        this.typemembre = typemembre;
        this.email = email;
        this.mpd = mpd;
        this.nomutil = nomutil;
        this.restoPref = restoPref;
        this.typecuisinePref = typecuisinePref;
    }
    public Membre(Typemembre typemembre, String email, String mpd, String nomutil, int restoPref, int typecuisinePref, Set restaurants, Set commentaires, Set typecuisines) {
       this.typemembre = typemembre;
       this.email = email;
       this.mpd = mpd;
       this.nomutil = nomutil;
       this.restoPref = restoPref;
       this.typecuisinePref = typecuisinePref;
       this.restaurants = restaurants;
       this.commentaires = commentaires;
       this.typecuisines = typecuisines;
    }
   
    public Integer getIdmembre() {
        return this.idmembre;
    }
    
    public void setIdmembre(Integer idmembre) {
        this.idmembre = idmembre;
    }
    public Typemembre getTypemembre() {
        return this.typemembre;
    }
    
    public void setTypemembre(Typemembre typemembre) {
        this.typemembre = typemembre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMpd() {
        return this.mpd;
    }
    
    public void setMpd(String mpd) {
        this.mpd = mpd;
    }
    public String getNomutil() {
        return this.nomutil;
    }
    
    public void setNomutil(String nomutil) {
        this.nomutil = nomutil;
    }
    public int getRestoPref() {
        return this.restoPref;
    }
    
    public void setRestoPref(int restoPref) {
        this.restoPref = restoPref;
    }
    public int getTypecuisinePref() {
        return this.typecuisinePref;
    }
    
    public void setTypecuisinePref(int typecuisinePref) {
        this.typecuisinePref = typecuisinePref;
    }
    public Set getRestaurants() {
        return this.restaurants;
    }
    
    public void setRestaurants(Set restaurants) {
        this.restaurants = restaurants;
    }
    public Set getCommentaires() {
        return this.commentaires;
    }
    
    public void setCommentaires(Set commentaires) {
        this.commentaires = commentaires;
    }
    public Set getTypecuisines() {
        return this.typecuisines;
    }
    
    public void setTypecuisines(Set typecuisines) {
        this.typecuisines = typecuisines;
    }




}


